# Generated by Django 4.2.5 on 2024-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buttons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("button_text", models.CharField(max_length=255)),
                ("audio_text", models.CharField(max_length=255)),
                ("user_id", models.IntegerField()),
            ],
        ),
    ]
